server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: customer

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/?authMechanism=SCRAM-SHA-1
      database: customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka